<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Goblin Gizmos - Terms of Service</title>

    <link rel="stylesheet" type="text/css" href="css/style.css">


    <script src="js/goblinScript.js"></script>
</head>

<body>

    <div class="page-wrap">

        <header>

            <div class="headerGrid">

                <!--This is the section with the logo, nav, and the user profile picture-->

                <div class="headerGridItem" id="logoFlex">
                    <img class="logoImage" src="img/goblinLogo.png" alt="a goblin face in a coin; the logo">



                </div>

                <div class="headerGridItem">
                    <h1>Goblin Gizmos</h1>
                </div>

                <div class="headerGridItem">
                    <nav>
                        <ol>
                            <li>
                                <a class="titleLink" href="index.php">Home</a>
                            </li>
                            <li>
                                <p>|</p>
                            </li>
                            <li>
                                <a class="titleLink" href="community.php">Community</a>
                            </li>
                            <li>
                                <p>|</p>
                            </li>
                            <li>
                                <a class="titleLink" href="search.php">Search</a>
                            </li>
                            <li>
                                <p>|</p>
                            </li>
                            <li>
                                <a class="titleLink" href="categories.php">Categories</a>
                            </li>
                        </ol>
                    </nav>
                </div>
                <div class="headerGridItem">

                    <a href="userProfile.php"> <img src="img/PFP.png" alt="Profile Picture"></a>
                    <!--PLACEHOLDER!! REPLACE LATER:  USER ICON-->
                </div>

            </div>
        </header>

        <div class="TOS">


            <!--Would this just be the straight text?? Are we picky??-->


            <h1> Goblin Gizmos - Terms of Service </h1>


            <p><b>Effective Date:</b> November 12, 2025</p>

            <p>
                This TOS was generated by AI and is fake
                Welcome to <b>Goblin Gizmos</b> (“Goblin Gizmos,” “we,” “our,” or “us”). These Terms of Service
                (“Terms”)
                govern
                your
                access to and use of our website, products, and services (collectively, the “Services”).
                By accessing or using Goblin Gizmos, you agree to be bound by these Terms and our Privacy Policy. If you
                do
                not
                agree, you may not use our Services.
            </p>


            <h2>1. Overview</h2>
            <p>
                Goblin Gizmos is an online platform where users can share and showcase their collectibles, connect with
                other
                enthusiasts, and participate in a community centered around collecting.
                These Terms outline your rights, responsibilities, and the conditions under which you may use our
                Services.
            </p>

            <h2>2. Eligibility</h2>
            <p>
                You must be at least 13 years old (or the minimum legal age in your jurisdiction) to use Goblin Gizmos.
                By
                using
                our
                Services, you represent and warrant that you meet this requirement and have the legal capacity to enter
                into
                this
                agreement.
            </p>

            <h2>
                3. Account Registration
            </h2>

            <p>
                To access certain features, you may need to create an account. When registering, you agree to:
                Provide accurate, complete, and current information.


                Maintain the confidentiality of your account credentials.


                Accept responsibility for all activities under your account.


                We reserve the right to suspend or terminate accounts that violate these Terms or our community
                standards.
            </p>

            <h2>
                4. User Content
            </h2>

            <p>
                a. Ownership
                You retain all rights to content you post, upload, or share through Goblin Gizmos (“User Content”).
                b. License to Goblin Gizmos
                By submitting User Content, you grant Goblin Gizmos a non-exclusive, worldwide, royalty-free,
                transferable,
                and
                sublicensable license to use, display, reproduce, distribute, and promote your content in connection
                with
                our
                Services. This license allows us to operate, market, and improve Goblin Gizmos.
                c. User Responsibilities
                You agree that your content will not:
                Infringe any third-party rights, including copyrights or trademarks.


                Contain unlawful, harmful, or misleading material.


                Include spam, scams, or other deceptive practices.


                We may remove or restrict access to content that violates these Terms or applicable law.

            </p>


            <h2>
                5. Prohibited Activities
            </h2>

            <p>
                When using Goblin Gizmos, you agree not to:
                Use the Services for commercial solicitation or unauthorized advertising.


                Harass, abuse, or threaten others.


                Impersonate any person or entity.


                Attempt to gain unauthorized access to the Site or its systems.


                Interfere with or disrupt the proper functioning of the Services.


                Violation of these provisions may result in account suspension or termination.
            </p>


            <h2>
                6. Intellectual Property
            </h2>

            <p>
                All content and materials provided through Goblin Gizmos (excluding User Content) — including logos,
                graphics,
                text,
                and software — are the property of Goblin Gizmos or its licensors and are protected by intellectual
                property
                laws.
                You may not copy, modify, distribute, or create derivative works from our materials without written
                permission.
            </p>

            <h2>
                7. Termination
            </h2>

            <p>
                We may suspend or terminate your access to the Services at any time, with or without notice, for conduct
                that we
                believe violates these Terms or harms our community.
                You may also delete your account at any time. Upon termination, sections of these Terms that by their
                nature
                should
                survive will remain in effect (including ownership, disclaimers, and limitations of liability).
            </p>


            <h2>
                8. Disclaimers and Limitation of Liability
            </h2>

            <p>
                Goblin Gizmos is provided on an “as is” and “as available” basis without warranties of any kind, express
                or
                implied.
                To the fullest extent permitted by law, Goblin Gizmos and its affiliates disclaim all warranties,
                including
                merchantability, fitness for a particular purpose, and non-infringement.
                Goblin Gizmos will not be liable for any indirect, incidental, consequential, or punitive damages
                arising
                from
                your
                use of or inability to use the Services.
            </p>


            <h2>
                9. Indemnification
            </h2>

            <p>
                You agree to defend, indemnify, and hold harmless Goblin Gizmos, its affiliates, employees, and agents
                from
                and
                against any claims, damages, or expenses arising out of your use of the Services or your violation of
                these
                Terms.
            </p>

            <h2>
                10. Changes to These Terms
            </h2>
            <p>
                We may update these Terms from time to time. The updated version will be posted on this page with the
                “Effective
                Date” revised accordingly. Continued use of the Services after updates means you accept the new Terms.

            </p>

            <h2>
                11. Governing Law
            </h2>

            <p>
                These Terms are governed by and construed in accordance with the laws of the State of Florida, without
                regard to
                its
                conflict of law principles.
                Any disputes arising under these Terms will be subject to the exclusive jurisdiction of the courts
                located
                in
                Florida.
            </p>


            <h2>
                12. Contact Us
            </h2>

            <p>
                If you have any questions or concerns about these Terms, please contact us at:
                goblingizmos@goblins.net
            </p>

        </div>

    </div>





    <footer>




        <img src="img/goblinLogo.png" id="bottomLogo" alt="a goblin face in a coin; the logo">
        <!--PLACEHOLDER!! REPLACE LATER: LOGO-->

        <div>
            <div class="footerFlex">
                <!--Bottom left-->
                <nav>
                    <div class="footerGrid">
                        <div class="footerGridItem1">

                            <ol>

                                <li>
                                    <a href="support.php" class="titleLink">Support</a>
                                </li>
                                <li>
                                    <p class="titleLink"> |</p>
                                </li>
                                <li>
                                    <a href="tos.php" class="titleLink">Terms of Service</a>
                                </li>
                            </ol>

                        </div>

                        <div class="footerGridItem2">
                            <ol>


                                <li><a href="https://x.com/"> <img src="img/TwitterLogo.png" class="iconImg"
                                            alt="X logo"></a></li>

                                <li><a href="https://www.instagram.com/"> <img src="img/instagram.png" class="iconImg"
                                            alt="Instagram logo"></a>
                                </li>

                                <li> <a href="https://www.facebook.com/"> <img src="img/facebook.png" class="iconImg"
                                            alt="Facebook logo"></a>
                                </li>

                                <!--This works, and now I'm too scared to touch it-->

                            </ol>

                        </div>
                    </div>
                </nav>

            </div>

        </div>

    </footer>

</body>

</html>